# Jekyll configuration
name: Formultitude
description: Formultitude is software for assignment of low weight molecular formula from high-resolution mass spectra.
url: https://pnnl-comp-mass-spec.github.io/Formultitude/

# Google Analytics
google_analytics: G-LXXKP1N66C
